//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetServer
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetClientRegistration", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetClientRegistration : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FriendlyNameField;
        
        private string IpAddressField;
        
        private string MacAddressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress
        {
            get
            {
                return this.IpAddressField;
            }
            set
            {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MacAddress
        {
            get
            {
                return this.MacAddressField;
            }
            set
            {
                this.MacAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetClientToken", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetClientToken : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdentifierField;
        
        private string TokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetClientIdentifier", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetClientIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdentifierField;
        
        private string WorkstationNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkstationName
        {
            get
            {
                return this.WorkstationNameField;
            }
            set
            {
                this.WorkstationNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetHearbeatEnum", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public enum FleetHearbeatEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoUpdates = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientUpdate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ControlUpdate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageUpdate = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileAvailable = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetFileIdentifier", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetFileIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FileNameField;
        
        private int FileSizeField;
        
        private string IdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileSize
        {
            get
            {
                return this.FileSizeField;
            }
            set
            {
                this.FileSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetFile", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetFile : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] FileContentsField;
        
        private string FileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContents
        {
            get
            {
                return this.FileContentsField;
            }
            set
            {
                this.FileContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetMessageIdentifier", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetMessageIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetMessage", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFleetService")]
public interface IFleetService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/RegisterClient", ReplyAction="http://tempuri.org/IFleetService/RegisterClientResponse")]
    FleetServer.FleetClientToken RegisterClient(FleetServer.FleetClientRegistration registrationModel);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/Heartbeat", ReplyAction="http://tempuri.org/IFleetService/HeartbeatResponse")]
    FleetServer.FleetHearbeatEnum Heartbeat(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] knownClients);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/QueryFiles", ReplyAction="http://tempuri.org/IFleetService/QueryFilesResponse")]
    FleetServer.FleetFileIdentifier[] QueryFiles(FleetServer.FleetClientToken token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/GetFile", ReplyAction="http://tempuri.org/IFleetService/GetFileResponse")]
    FleetServer.FleetFile GetFile(FleetServer.FleetClientToken token, FleetServer.FleetFileIdentifier fileId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendFileSingleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendFileSingleRecipientResponse")]
    bool SendFileSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetFile file);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendFileMultipleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendFileMultipleRecipientResponse")]
    bool SendFileMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetFile file);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/QueryMessages", ReplyAction="http://tempuri.org/IFleetService/QueryMessagesResponse")]
    FleetServer.FleetMessageIdentifier[] QueryMessages(FleetServer.FleetClientToken token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/GetMessage", ReplyAction="http://tempuri.org/IFleetService/GetMessageResponse")]
    FleetServer.FleetMessage GetMessage(FleetServer.FleetClientToken token, FleetServer.FleetMessageIdentifier fileId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendMessageSingleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendMessageSingleRecipientResponse")]
    bool SendMessageSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetMessage msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendMessageMultipleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendMessageMultipleRecipientResponse")]
    bool SendMessageMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetMessage msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IFleetServiceChannel : IFleetService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class FleetServiceClient : System.ServiceModel.ClientBase<IFleetService>, IFleetService
{
    
    public FleetServiceClient()
    {
    }
    
    public FleetServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FleetServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FleetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FleetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FleetServer.FleetClientToken RegisterClient(FleetServer.FleetClientRegistration registrationModel)
    {
        return base.Channel.RegisterClient(registrationModel);
    }
    
    public FleetServer.FleetHearbeatEnum Heartbeat(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] knownClients)
    {
        return base.Channel.Heartbeat(token, knownClients);
    }
    
    public FleetServer.FleetFileIdentifier[] QueryFiles(FleetServer.FleetClientToken token)
    {
        return base.Channel.QueryFiles(token);
    }
    
    public FleetServer.FleetFile GetFile(FleetServer.FleetClientToken token, FleetServer.FleetFileIdentifier fileId)
    {
        return base.Channel.GetFile(token, fileId);
    }
    
    public bool SendFileSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetFile file)
    {
        return base.Channel.SendFileSingleRecipient(token, recipient, file);
    }
    
    public bool SendFileMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetFile file)
    {
        return base.Channel.SendFileMultipleRecipient(token, recipients, file);
    }
    
    public FleetServer.FleetMessageIdentifier[] QueryMessages(FleetServer.FleetClientToken token)
    {
        return base.Channel.QueryMessages(token);
    }
    
    public FleetServer.FleetMessage GetMessage(FleetServer.FleetClientToken token, FleetServer.FleetMessageIdentifier fileId)
    {
        return base.Channel.GetMessage(token, fileId);
    }
    
    public bool SendMessageSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetMessage msg)
    {
        return base.Channel.SendMessageSingleRecipient(token, recipient, msg);
    }
    
    public bool SendMessageMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetMessage msg)
    {
        return base.Channel.SendMessageMultipleRecipient(token, recipients, msg);
    }
}
